/*
 * shifter.c
 *
 * Created: 7/15/2018 4:21:33 PM
 *  Author: Mohab
 */ 



#include "Shifter.h"


void Shifter_Init(void){
	SHIFTER_DATA_DIRECTION_REG |= (1<<SHIFTER_DATA_PIN_NUM); //output
	SHIFTER_CLK_DIRECTION_REG |=(1<<SHIFTER_CLK_PIN_NUM);
    SHIFTER_LATCH_DISPLAY_DIRECTION_REG |=(1<<SHIFTER_LATCH_DISPLAY_PIN_NUM);
	SHIFTER_LATCH_OUTPUT_DIRECTION_REG |=(1<<SHIFTER_LATCH_OUTPUT_PIN_NUM);
	
	SHIFTER_RESET_DISPLAY_DIRECTION_REG |=(1<<SHIFTER_RESET_DISPLAY_PIN_NUM);
	/*SHIFTER_RESET_OUTPUT_DIRECTION_REG |=(1<<SHIFTER_RESET_OUTPUT_PIN_NUM);*/
	SHIFTER_RESET_OUTPUT_DIRECTION_REG |=(1<<SHIFTER_RESET_OUTPUT_PIN_NUM);
	HW_RESET_BIT(SHIFTER_CLK_DATA_REG,SHIFTER_CLK_PIN_NUM);
	HW_RESET_BIT(SHIFTER_LATCH_DISPLAY_DATA_REG,SHIFTER_LATCH_DISPLAY_PIN_NUM);
	HW_RESET_BIT(SHIFTER_LATCH_OUTPUT_DATA_REG,SHIFTER_LATCH_OUTPUT_PIN_NUM);
	HW_SET_BIT(SHIFTER_RESET_DISPLAY_DATA_REG,SHIFTER_RESET_DISPLAY_PIN_NUM);
	HW_SET_BIT(SHIFTER_RESET_OUTPUT_DATA_REG,SHIFTER_RESET_OUTPUT_PIN_NUM);
	
	
}


void ShiftOut_8bit(uint8_t bitOrder, uint8_t val){

	for (uint8_t i = 0; i < 8; i++){
		if (bitOrder == LSBFIRST){
			//output serial data
			HW_WRITE_REG8_MASKED(SHIFTER_DATA_DATA_REG,
					((!!(val & (1 << i)))<<SHIFTER_DATA_PIN_NUM),
						(1<<SHIFTER_DATA_PIN_NUM));
			//clk
			HW_SET_BIT(SHIFTER_CLK_DATA_REG,SHIFTER_CLK_PIN_NUM);
		
			HW_RESET_BIT(SHIFTER_CLK_DATA_REG,SHIFTER_CLK_PIN_NUM);
		
		}
		else{
			
		}
	}
}

void ShiftOut_16bit(uint8_t bitOrder, uint16_t val){

	for (uint8_t i = 0; i < 16; i++){
		if (bitOrder == LSBFIRST){
			//output serial data
			HW_WRITE_REG8_MASKED(SHIFTER_DATA_DATA_REG,
									((!!(val & (1 << i)))<<SHIFTER_DATA_PIN_NUM),
												(1<<SHIFTER_DATA_PIN_NUM));
			//clk
			HW_SET_BIT(SHIFTER_CLK_DATA_REG,SHIFTER_CLK_PIN_NUM);
			
			HW_RESET_BIT(SHIFTER_CLK_DATA_REG,SHIFTER_CLK_PIN_NUM);
			
		}
		else{
			
		}
	}
}


void Shifter_Display_Latch(void){
	HW_SET_BIT(SHIFTER_LATCH_DISPLAY_DATA_REG,SHIFTER_LATCH_DISPLAY_PIN_NUM);
	HW_RESET_BIT(SHIFTER_LATCH_DISPLAY_DATA_REG,SHIFTER_LATCH_DISPLAY_PIN_NUM);
	
}
void Shifter_Output_Latch(void){
	HW_SET_BIT(SHIFTER_LATCH_OUTPUT_DATA_REG,SHIFTER_LATCH_OUTPUT_PIN_NUM);	
	HW_RESET_BIT(SHIFTER_LATCH_OUTPUT_DATA_REG,SHIFTER_LATCH_OUTPUT_PIN_NUM);
}

		
	
	
